### ISSUE TITLE
Android app: java.lang.NullPointerException: Parameter specified as non-null is null

### ISSUE THREAD

**Issue by lefoumalade451** [passbolt/mobile-passbolt-android#5]
Hello Passbolt,
I am having issue pairing my android device to my dockerized passbolt, once the QR code are scanned by the app, I type my password and I got "Devices pair successfully" then it goes to login page again, I put the password etc...

Passbolt App log:
```
Passbolt Android logs: 
Device: OnePlus AC2003
Android 12 (31)
Passbolt 1.11.0-14

16:58:58 --> PUT https://passbolt-url.com/mobile/transfers/UUID/UUID.json h2 (41-byte body)
16:58:58 <-- 200 https://passbolt-url.com/mobile/transfers/UUID/UUID.json (73ms, unknown-length body)
16:58:58 --> PUT https://passbolt-url.com/mobile/transfers/UUID/UUID.json h2 (41-byte body)
16:58:59 <-- 200 https://passbolt-url.com/mobile/transfers/UUID/UUID.json (164ms, unknown-length body)
16:58:59 --> PUT https://passbolt-url.com/mobile/transfers/UUID/UUID.json h2 (41-byte body)
16:58:59 <-- 200 https://passbolt-url.com/mobile/transfers/UUID/UUID.json (61ms, unknown-length body)
16:59:00 --> PUT https://passbolt-url.com/mobile/transfers/UUID/UUID.json h2 (41-byte body)
16:59:00 <-- 200 https://passbolt-url.com/mobile/transfers/UUID/UUID.json (56ms, unknown-length body)
16:59:00 Saving private key.
16:59:00 --> PUT https://passbolt-url.com/mobile/transfers/UUID/UUID.json?contain%5Buser.profile%5D=1 h2 (38-byte body)
16:59:00 <-- 200 https://passbolt-url.com/mobile/transfers/UUID/UUID.json?contain%5Buser.profile%5D=1 (76ms, unknown-length body)
16:59:01 Checking biometry state
16:59:02 --> GET https://passbolt-url.com/img/avatar/user_medium.png h2
16:59:02 <-- 200 https://passbolt-url.com/img/avatar/user_medium.png (4ms, 2921-byte body)
16:59:02 Received fill request
16:59:02 Visiting view node with id: -1 scheme + domain: null://null package: null content description: null autofill hints null hint: null html autocomplete attr: null important for autofill: 0 input type: 0 
16:59:02 Visiting view node with id: 2131361858 scheme + domain: null://null package: com.passbolt.mobile.android content description: null autofill hints null hint: null html autocomplete attr: null important for autofill: 0 input type: 0 
16:59:02 Visiting view node with id: 2131361874 scheme + domain: null://null package: com.passbolt.mobile.android content description: null autofill hints null hint: null html autocomplete attr: null important for autofill: 0 input type: 0 
16:59:02 Visiting view node with id: 2131362129 scheme + domain: null://null package: com.passbolt.mobile.android content description: null autofill hints null hint: null html autocomplete attr: null important for autofill: 0 input type: 0 
16:59:02 Visiting view node with id: 2131362129 scheme + domain: null://null package: com.passbolt.mobile.android content description: null autofill hints null hint: null html autocomplete attr: null important for autofill: 0 input type: 0 
16:59:02 Visiting view node with id: 2131362584 scheme + domain: null://null package: com.passbolt.mobile.android content description: null autofill hints null hint: null html autocomplete attr: null important for autofill: 0 input type: 0 
16:59:02 Visiting view node with id: -1 scheme + domain: null://null package: null content description: null autofill hints null hint: null html autocomplete attr: null important for autofill: 1 input type: 0 
16:59:02 Visiting view node with id: 2131362310 scheme + domain: null://null package: com.passbolt.mobile.android content description: null autofill hints null hint: null html autocomplete attr: null important for autofill: 1 input type: 0 
16:59:02 Visiting view node with id: 2131362070 scheme + domain: null://null package: com.passbolt.mobile.android content description: null autofill hints null hint: null html autocomplete attr: null important for autofill: 1 input type: 0 
16:59:02 Visiting view node with id: 2131362047 scheme + domain: null://null package: com.passbolt.mobile.android content description: null autofill hints null hint: null html autocomplete attr: null important for autofill: 1 input type: 0 
16:59:02 Visiting view node with id: 2131362357 scheme + domain: null://null package: com.passbolt.mobile.android content description: null autofill hints null hint: null html autocomplete attr: null important for autofill: 0 input type: 0 
16:59:02 Visiting view node with id: 2131362581 scheme + domain: null://null package: com.passbolt.mobile.android content description: null autofill hints null hint: null html autocomplete attr: null important for autofill: 1 input type: 0 
16:59:02 Visiting view node with id: 2131362561 scheme + domain: null://null package: com.passbolt.mobile.android content description: null autofill hints null hint: null html autocomplete attr: null important for autofill: 1 input type: 0 
16:59:02 Visiting view node with id: 2131362188 scheme + domain: null://null package: com.passbolt.mobile.android content description: null autofill hints null hint: null html autocomplete attr: null important for autofill: 1 input type: 129 
16:59:02 Visiting view node with id: -1 scheme + domain: null://null package: null content description: null autofill hints null hint: null html autocomplete attr: null important for autofill: 0 input type: 0 
16:59:02 Visiting view node with id: -1 scheme + domain: null://null package: null content description: null autofill hints null hint: null html autocomplete attr: null important for autofill: 0 input type: 0 
16:59:02 Visiting view node with id: 2131362575 scheme + domain: null://null package: com.passbolt.mobile.android content description: null autofill hints null hint: null html autocomplete attr: null important for autofill: 1 input type: 0 
16:59:02 Visiting view node with id: 2131361922 scheme + domain: null://null package: com.passbolt.mobile.android content description: null autofill hints null hint: null html autocomplete attr: null important for autofill: 1 input type: 0 
16:59:02 Visiting view node with id: 2131361920 scheme + domain: null://null package: com.passbolt.mobile.android content description: null autofill hints null hint: null html autocomplete attr: null important for autofill: 1 input type: 0 
16:59:02 Visiting view node with id: 2131362128 scheme + domain: null://null package: com.passbolt.mobile.android content description: null autofill hints null hint: null html autocomplete attr: null important for autofill: 1 input type: 0 
16:59:02 Parsed domain: 
16:59:02 Did not find any autofillable views
16:59:10 Passphrase cache cleared
16:59:10 Passphrase cached
16:59:10 Getting server pgp and rsa keys
16:59:10 --> GET https://passbolt-url.com/auth/verify.json h2
16:59:10 <-- 200 https://passbolt-url.com/auth/verify.json (76ms, unknown-length body)
16:59:10 Uncaught exception in thread: main
java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter publicKey
	at com.passbolt.mobile.android.feature.authentication.auth.usecase.GetServerPublicPgpKeyUseCase$Output$Success.<init>(Unknown Source:2)
	at com.passbolt.mobile.android.feature.authentication.auth.usecase.GetServerPublicPgpKeyUseCase.execute(GetServerPublicPgpKeyUseCase.kt:38)
	at com.passbolt.mobile.android.feature.authentication.auth.usecase.GetServerPublicPgpKeyUseCase$execute$1.invokeSuspend(Unknown Source:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8212)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@a6284b2, Dispatchers.Main]

java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter publicKey
	at com.passbolt.mobile.android.feature.authentication.auth.usecase.GetServerPublicPgpKeyUseCase$Output$Success.<init>(Unknown Source:2)
	at com.passbolt.mobile.android.feature.authentication.auth.usecase.GetServerPublicPgpKeyUseCase.execute(GetServerPublicPgpKeyUseCase.kt:38)
	at com.passbolt.mobile.android.feature.authentication.auth.usecase.GetServerPublicPgpKeyUseCase$execute$1.invokeSuspend(Unknown Source:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8212)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@a6284b2, Dispatchers.Main]
16:59:10 Uncaught exception in thread: main
java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter publicKey
	at com.passbolt.mobile.android.feature.authentication.auth.usecase.GetServerPublicPgpKeyUseCase$Output$Success.<init>(Unknown Source:2)
	at com.passbolt.mobile.android.feature.authentication.auth.usecase.GetServerPublicPgpKeyUseCase.execute(GetServerPublicPgpKeyUseCase.kt:38)
	at com.passbolt.mobile.android.feature.authentication.auth.usecase.GetServerPublicPgpKeyUseCase$execute$1.invokeSuspend(Unknown Source:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8212)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@a6284b2, Dispatchers.Main]

java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter publicKey
	at com.passbolt.mobile.android.feature.authentication.auth.usecase.GetServerPublicPgpKeyUseCase$Output$Success.<init>(Unknown Source:2)
	at com.passbolt.mobile.android.feature.authentication.auth.usecase.GetServerPublicPgpKeyUseCase.execute(GetServerPublicPgpKeyUseCase.kt:38)
	at com.passbolt.mobile.android.feature.authentication.auth.usecase.GetServerPublicPgpKeyUseCase$execute$1.invokeSuspend(Unknown Source:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8212)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@a6284b2, Dispatchers.Main]
16:59:10 File logging tree planted
16:59:12 Checking biometry state
17:01:25 Checking biometry state
17:01:26 Checking biometry state
```

Docker logs:
```
passbolt-passbolt-1     | 2023-01-22 17:31:26,625 INFO reaped unknown pid 2046 (exit status 0)
passbolt-passbolt-1     | 2023-01-22 17:31:26,625 INFO reaped unknown pid 2048 (exit status 0)
passbolt-passbolt-1     | 2023-01-22 17:31:26,626 INFO reaped unknown pid 2051 (exit status 0)
passbolt-passbolt-1     | 2023-01-22 17:31:26,626 INFO reaped unknown pid 2053 (exit status 0)
passbolt-passbolt-1     | 2023-01-22 17:31:26,626 INFO reaped unknown pid 2055 (exit status 0)
passbolt-passbolt-1     | 2023-01-22 17:31:26,626 INFO reaped unknown pid 2057 (exit status 0)
passbolt-passbolt-1     | 2023-01-22 17:31:26,626 INFO reaped unknown pid 2059 (exit status 0)
passbolt-passbolt-1     | 2023-01-22 17:31:26,626 INFO reaped unknown pid 2062 (exit status 0)
```

Many thanks!

**Comment by marcin-michalek-miquido** [comment]
hello @lefoumalade451, from the logs it looks like there is an issue with the server public key configuration - your server does not return the required public key data via the API ([this endpoint](https://api-reference.passbolt.com/#/Auth/get_auth_verify_json) contains `null` in the `body.keydata` response filed). I asked the support team to provide more feedback on how to check this here.

**Comment by lefoumalade451** [comment]
Hello thank you for responding!
I also want to say that both my passbolt instance on website and extension(Chrome based) works fine on my computers, so I don't now why the API does not return the pubkey when I try the android app.

Thank you!

**Comment by lefoumalade451** [comment]
hello! any news?

**Comment by claytontstevenson** [comment]
Hey @lefoumalade451 a thing to try to see where the issue could be is to run the healthcheck, instructions for how to do this on docker can be found [here](https://help.passbolt.com/faq/hosting/troubleshoot-docker). Once you've done that can you post the output?

**Comment by lefoumalade451** [comment]
I am running the latest version of passbolt on docker, so I use: `docker exec -it passbolt su -s /bin/bash -c '/usr/share/php/passbolt/bin/cake passbolt healthcheck' www-data` and I got this output

```
     ____                  __          ____
    / __ \____  _____ ____/ /_  ____  / / /_
   / /_/ / __ `/ ___/ ___/ __ \/ __ \/ / __/
  / ____/ /_/ (__  |__  ) /_/ / /_/ / / /
 /_/    \__,_/____/____/_.___/\____/_/\__/

 Open source password manager for teams
-------------------------------------------------------------------------------
 Healthcheck shell......Exception: No OpenPGP marker found.
In [/usr/share/php/passbolt/src/Utility/OpenPGP/Traits/OpenPGPBackendArmoredParseTrait.php, line 34]
```

**Comment by lefoumalade451** [comment]
Thanks for answering, to be honest I just recreate a fresh instance of passbolt with docker, and everything is working great now for the app.

I think the problem was that when I migrate my instance to docker, the GPG keys were in binary format, when recreating a fresh new instance I notice the GPG keys was in plain text.

Thank!
